### PR TITLE
CR/NEED - update chrome extension to be a slideshow

### PR DESCRIPTION
**Pull request by fabien-d**
#### What does this PR do?

Updated chrome extension to follow the same look and feel as the coming Chromecast application.
#### Todos:
- ~~Currently using my collection as the source for art. We should curate a list from the featured art section and use those.~~ Leaving the hard coded data for now. Will update when we get the public API
#### Any background context you want to provide?

The extension can be locally tested in developer mode but cannot be distributed until it's been published to the Google Web Store.
#### Screenshots (if appropriate)

image

### CODE REVIEW

**Comment by fabien-d** [comment]
FLOW message for @ryanjohnson-me

> The PR needs to be reviewed by a peer

**Comment by ryanjohnson-me** [comment]
:+1:

**Comment by fabien-d** [comment]
@ryanjohnson-me @christaggart thoughts on the "todo"? Should I use the last 30 featured art for now?

**Comment by ryanjohnson-me** [comment]
Can it cycle just the top most popular?

**Comment by fabien-d** [comment]
We don't have a public API yet, it's a no go for dynamic content (atm)

**Pull request merged**
